# Generated by Django 3.0.3 on 2021-08-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200725_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
