# Generated by Django 3.0.3 on 2021-08-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_desc',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='header_keys',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
