# Generated by Django 3.0.3 on 2021-08-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210824_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lead_image',
            field=models.ImageField(default='', upload_to='public/media/articles-images/%Y/'),
            preserve_default=False,
        ),
    ]
