# Generated by Django 2.1.1 on 2018-09-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='icon_name',
            field=models.CharField(default='RS.png', max_length=10),
            preserve_default=False,
        ),
    ]
