# Generated by Django 2.1.1 on 2018-09-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_country_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.Country')),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='days_lasted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='role',
            field=models.CharField(choices=[('1st', 'First'), ('2nd', 'Assistant')], default='1st', max_length=3),
        ),
        migrations.AddField(
            model_name='employment',
            name='still_hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manager',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='icon_name',
            field=models.CharField(default='default_cup200.png', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employment',
            name='manager',
            field=models.ForeignKey(default=333, on_delete=django.db.models.deletion.CASCADE, to='managers.Manager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employment',
            name='team',
            field=models.ForeignKey(default=333, on_delete=django.db.models.deletion.CASCADE, to='managers.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.Country'),
        ),
        migrations.AddField(
            model_name='manager',
            name='city_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.City'),
        ),
    ]
