# Generated by Django 2.1.1 on 2018-09-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_auto_20180922_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='icon_name',
            field=models.CharField(default='default_cup200.png', max_length=10),
        ),
    ]
