# Generated by Django 2.1.1 on 2018-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_auto_20180923_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='photo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
