# Generated by Django 2.1.1 on 2018-09-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0007_manager_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='photo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
