# Generated by Django 2.1.1 on 2018-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_auto_20180923_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
