# Generated by Django 2.1.1 on 2018-09-30 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_team_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='date_end',
            field=models.DateField(default=datetime.date(2019, 6, 30)),
        ),
        migrations.AddField(
            model_name='season',
            name='date_start',
            field=models.DateField(default=datetime.date(2018, 7, 1)),
        ),
    ]
