# Generated by Django 2.1.1 on 2018-09-30 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0010_auto_20180930_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='date_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
