# Generated by Django 2.1.1 on 2018-10-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0013_externallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='managers.Manager'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='managers.Employment'),
        ),
    ]
