# Generated by Django 2.1 on 2018-10-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0014_auto_20181009_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name_full',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_short',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
