# Generated by Django 2.1 on 2018-10-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0016_auto_20181014_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='date_finish_approx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employment',
            name='date_start_approx',
            field=models.BooleanField(default=False),
        ),
    ]
