# Generated by Django 2.1.2 on 2018-10-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0017_auto_20181014_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirings', to='managers.Team'),
        ),
    ]
