# Generated by Django 2.1.2 on 2018-10-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0018_auto_20181021_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseason',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='managers.Season'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='managers.Team'),
        ),
    ]
