# Generated by Django 2.1.3 on 2018-11-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0019_auto_20181021_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
