# Generated by Django 2.1.2 on 2019-01-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0021_country_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='years',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
