# Generated by Django 2.1.2 on 2019-01-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0022_auto_20190101_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='icon_name',
            field=models.CharField(default='default_cup200.png', max_length=15),
        ),
    ]
