# Generated by Django 2.1.2 on 2019-01-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0026_team_is_national'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='date_finish_approx',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='date_start_approx',
        ),
    ]
