# Generated by Django 2.1 on 2019-01-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0027_auto_20190106_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
