# Generated by Django 2.1 on 2019-01-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0028_auto_20190113_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseason',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='managers.Season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='managers.Team'),
            preserve_default=False,
        ),
    ]
