# Generated by Django 2.1 on 2019-04-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0030_auto_20190113_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=55),
        ),
    ]
