# Generated by Django 2.1 on 2019-04-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0032_auto_20190420_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(default='fake', max_length=55),
            preserve_default=False,
        ),
    ]
