# Generated by Django 2.1.1 on 2019-07-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0035_auto_20190713_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseason',
            name='season',
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='team',
        ),
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(to='managers.Team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='icon_name',
            field=models.CharField(default='defaultcup_200.png', max_length=20),
        ),
        migrations.DeleteModel(
            name='TeamSeason',
        ),
    ]
