# Generated by Django 2.1.1 on 2019-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0037_auto_20190720_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(max_length=55, unique=True),
        ),
    ]
