# Generated by Django 3.1.4 on 2020-12-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0039_auto_20200229_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='next_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='managers.season'),
        ),
        migrations.AddField(
            model_name='season',
            name='prev_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='managers.season'),
        ),
    ]
