# Generated by Django 3.0.3 on 2021-08-04 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0040_auto_20201228_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='date_end',
            field=models.DateField(default=datetime.date(2022, 6, 30)),
        ),
        migrations.AlterField(
            model_name='season',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 7, 1)),
        ),
        migrations.CreateModel(
            name='SeasonMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('show', models.BooleanField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.Season')),
            ],
        ),
    ]
