# Generated by Django 3.0.3 on 2021-08-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0041_auto_20210804_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonmenu',
            old_name='priority',
            new_name='order',
        ),
    ]
